Repository quotient-im/libQuotient, pull requests merged in 2020-12, with the labels that each got.

#416 Add feature summary to cmake file
  CMakeLists.txt
Labels: building/packaging

#423 Room: fix breakage in internal member map
  lib/room.cpp
Labels: bug, crash

#430 Fix use-after-free of QNetworkReply in BaseJob
  lib/jobs/basejob.cpp
Labels: bug, crash

#425 Add support for stickers
  CMakeLists.txt
  lib/events/stickerevent.cpp
  lib/events/stickerevent.h
Labels: enhancement
