Repository quotient-im/libQuotient, pull requests merged in 2021-01, with the labels that each got.

#434 Migrate to GitHub Actions
  .github/workflows/ci.yml
Labels: building/packaging

#436 Use CMAKE_INSTALL_DATADIR instead of hard-coding share
  CMakeLists.txt
Labels: bug, building/packaging

#417 Enable QT_NO_URL_CAST_FROM_STRING and QT_STRICT_ITERATORS.
  CMakeLists.txt
  lib/events/eventcontent.cpp
  lib/events/eventcontent.h
  lib/events/roommemberevent.cpp
  lib/jobs/basejob.cpp
  lib/room.cpp
  lib/ssosession.cpp
Labels: enhancement

#440 Add more properties to CallCandidateEvent
  CMakeLists.txt
  autotests/CMakeLists.txt
  autotests/callcandidateseventtest.cpp
  autotests/callcandidateseventtest.h
  lib/events/callcandidatesevent.h
  quotest/.valgrind.supp
  quotest/CMakeLists.txt
  quotest/quotest.cpp
  tests/CMakeLists.txt
Labels: enhancement
