Repository quotient-im/libQuotient, pull requests merged in 2022-11, with the labels that each got.

#589 Manage key and random material using OpenSSL facilities
  .clang-tidy
  CMakeLists.txt
  autotests/testgroupsession.cpp
  autotests/testkeyverification.cpp
  autotests/testolmaccount.cpp
  autotests/testolmsession.cpp
  gtad/gtad.yaml
  lib/connection.cpp
  lib/connection.h
  lib/csapi/keys.h
  lib/database.cpp
  lib/database.h
  lib/e2ee/e2ee.h
  lib/e2ee/e2ee_common.cpp
  lib/e2ee/e2ee_common.h
  lib/e2ee/qolmaccount.cpp
  lib/e2ee/qolmaccount.h
  lib/e2ee/qolminboundsession.cpp
  lib/e2ee/qolminboundsession.h
  lib/e2ee/qolmoutboundsession.cpp
  lib/e2ee/qolmoutboundsession.h
  lib/e2ee/qolmsession.cpp
  lib/e2ee/qolmsession.h
  lib/e2ee/qolmutils.cpp
  lib/e2ee/qolmutils.h
  lib/events/encryptedevent.cpp
  lib/events/encryptionevent.cpp
  lib/events/filesourceinfo.cpp
  lib/expected.h
  lib/keyverificationsession.cpp
  lib/room.cpp
Labels: bug, enhancement

#590 Limit attempts of recovering from broken olm sessions
  lib/connection.cpp
Labels: bug

#595 Also send encryption keys to invited users
  lib/connection.cpp
  lib/connection.h
  lib/room.cpp
Labels: enhancement
