Repository quotient-im/libQuotient, pull requests merged in 2023-07, with the labels that each got.

#679 One last documentation refresh
  CODE_GENERATION.md
  README.md
Labels: documentation

#680 Use RoomPinnedEventsEvent instead of the old name
  Quotient/room.cpp
Labels: enhancement

#682 Fix session verification
  Quotient/keyverificationsession.cpp
Labels: bug/fix
