Repository quotient-im/libQuotient, pull requests merged in 2023-04, with the labels that each got.

#639 Don't crash in AccountRegistry::get
  lib/accountregistry.cpp
Labels: bug/fix

#640 Use the fixed MAC when possible (MSC3783)
  lib/converters.h
  lib/events/keyverificationevent.h
  lib/keyverificationsession.cpp
  lib/keyverificationsession.h
Labels: enhancement

#647 Change "user has no name" log from warning to debug
  Quotient/room.cpp
Labels: enhancement

#646 Make Qt5 and Qt6 versions of libQuotient co-installable
  CMakeLists.txt
  autotests/CMakeLists.txt
  quotest/CMakeLists.txt
Labels: building/packaging
