Repository quotient-im/libQuotient, pull requests merged in 2023-06, with the labels that each got.

#666 Fix redactions
  Quotient/events/event.h
  Quotient/room.cpp
  quotest/quotest.cpp
Labels: bug/fix, enhancement

#667 Event::type() deprecation + cleanup
  Quotient/connection.cpp
  Quotient/events/event.h
  Quotient/events/roompowerlevelsevent.cpp
  Quotient/events/roompowerlevelsevent.h
  Quotient/room.cpp
  Quotient/room.h
  autotests/setup-tests.sh
Labels: enhancement

#671 asKeyValueRange: support accepting rvalues
  Quotient/connectionencryptiondata_p.cpp
  Quotient/e2ee/qolmaccount.cpp
  Quotient/util.h
  autotests/testolmaccount.cpp
Labels: enhancement

#672 Tighten up logging categories stuff
  .clang-format
  CMakeLists.txt
  CONTRIBUTING.md
  Quotient/accountregistry.cpp
  Quotient/avatar.cpp
  Quotient/connection.cpp
  Quotient/connectiondata.cpp
  Quotient/connectionencryptiondata_p.cpp
  Quotient/connectionencryptiondata_p.h
  Quotient/converters.cpp
  Quotient/database.cpp
  Quotient/e2ee/e2ee_common.cpp
  Quotient/e2ee/qolmaccount.cpp
  Quotient/e2ee/qolminboundsession.cpp
  Quotient/e2ee/qolmoutboundsession.cpp
  Quotient/e2ee/qolmsession.cpp
  Quotient/events/callevents.cpp
  Quotient/events/encryptionevent.cpp
  Quotient/events/event.cpp
  Quotient/events/eventcontent.cpp
  Quotient/events/eventrelation.cpp
  Quotient/events/filesourceinfo.cpp
  Quotient/events/receiptevent.cpp
  Quotient/events/roomevent.cpp
  Quotient/events/roommemberevent.cpp
  Quotient/events/roommessageevent.cpp
  Quotient/events/stateevent.cpp
  Quotient/eventstats.cpp
  Quotient/jobs/basejob.cpp
  Quotient/jobs/basejob.h
  Quotient/jobs/downloadfilejob.cpp
  Quotient/jobs/mediathumbnailjob.cpp
  Quotient/jobs/syncjob.cpp
  Quotient/keyverificationsession.cpp
  Quotient/logging.cpp
  Quotient/logging.h
  Quotient/logging_categories_p.h
  Quotient/networkaccessmanager.cpp
  Quotient/room.cpp
  Quotient/settings.cpp
  Quotient/ssosession.cpp
  Quotient/syncdata.cpp
  Quotient/uri.cpp
  Quotient/user.cpp
  Quotient/util.h
  README.md
Labels: enhancement

#675 Add connections in AccountRegistry::invokeLogin()
  Quotient/accountregistry.cpp
Labels: regression
