Repository quotient-im/libQuotient, pull requests merged in 2023-03, with the labels that each got.

#627 Keep track of read bytes on MxcReply and reimplement bytesAvailable
  lib/mxcreply.cpp
  lib/mxcreply.h
Labels: bug

#629 Send megolm key when there is no new olm session
  lib/connection.cpp
Labels: bug/fix

#636 Kitsune/minor connection tweaks
  lib/accountregistry.cpp
  lib/accountregistry.h
  lib/connection.cpp
  lib/connection.h
  lib/connection_p.h
  lib/events/encryptedevent.cpp
  lib/events/encryptedevent.h
Labels: enhancement
