Repository quotient-im/libQuotient, pull requests merged in 2023-02, with the labels that each got.

#617 Unexport private classes
  lib/avatar.cpp
  lib/connection.cpp
  lib/jobs/basejob.cpp
  lib/jobs/downloadfilejob.cpp
  lib/mxcreply.cpp
  lib/networkaccessmanager.cpp
  lib/room.cpp
  lib/ssosession.cpp
  lib/user.cpp
Labels: building/packaging

#619 Disable exception support where not needed
  CMakeLists.txt
  autotests/CMakeLists.txt
Labels: building/packaging

#621 Consistently mark QLatin1String constants as constexpr inline
  lib/e2ee/e2ee_common.h
  lib/events/accountdataevents.h
  lib/events/encryptedevent.h
  lib/events/event.h
  lib/events/eventrelation.h
  lib/events/keyverificationevent.h
  lib/events/simplestateevents.h
  lib/syncdata.h
Labels: enhancement, building/packaging

#622 Consistently use the QLatin1String key constants
  lib/events/event.h
  lib/events/eventrelation.cpp
  lib/events/reactionevent.h
  lib/events/roomevent.cpp
  lib/events/roommessageevent.cpp
  lib/events/stateevent.h
  lib/room.cpp
Labels: enhancement

#623 Distinguish between public and private link interface
  CMakeLists.txt
Labels: enhancement, building/packaging

#620 Build without qt casts
  CMakeLists.txt
  autotests/callcandidateseventtest.cpp
  autotests/testkeyverification.cpp
  autotests/testolmaccount.cpp
  autotests/testolmutility.cpp
  autotests/testutils.h
  gtad/operation.h.mustache
  lib/accountregistry.cpp
  lib/avatar.cpp
  lib/connection.cpp
  lib/connection.h
  lib/connectiondata.cpp
  lib/converters.h
  lib/csapi/content-repo.h
  lib/database.cpp
  lib/e2ee/e2ee_common.h
  lib/e2ee/qolmaccount.cpp
  lib/e2ee/qolminboundsession.cpp
  lib/e2ee/qolmsession.cpp
  lib/events/encryptedevent.cpp
  lib/events/eventcontent.cpp
  lib/events/eventcontent.h
  lib/events/filesourceinfo.cpp
  lib/events/keyverificationevent.h
  lib/events/roomkeyevent.h
  lib/events/roommessageevent.cpp
  lib/events/roompowerlevelsevent.cpp
  lib/jobs/basejob.cpp
  lib/jobs/downloadfilejob.cpp
  lib/jobs/mediathumbnailjob.cpp
  lib/jobs/syncjob.cpp
  lib/keyverificationsession.cpp
  lib/networkaccessmanager.cpp
  lib/quotient_common.h
  lib/room.cpp
  lib/settings.cpp
  lib/settings.h
  lib/ssosession.cpp
  lib/syncdata.cpp
  lib/uri.cpp
  lib/uriresolver.cpp
  lib/user.cpp
  lib/util.cpp
  quotest/quotest.cpp
Labels: enhancement, building/packaging
