Repository quotient-im/libQuotient, pull requests merged in 2023-05, with the labels that each got.

#650 Fix CMake configuration when using Qt6
  cmake/QuotientConfig.cmake.in
Labels: building/packaging

#651 Fix Matrix URI parsing
  Quotient/uri.cpp
Labels: bug/fix

#654 Fix E2EE build with LibreSSL
  Quotient/e2ee/e2ee_common.cpp
Labels: enhancement

#656 Fix dependency finding in the CMake config file
  CMakeLists.txt
  cmake/QuotientConfig.cmake.in
Labels: building/packaging

#658 Fix generating an invalid CMake config file with unset BUILD_SHARED_LIBS
  CMakeLists.txt
Labels: bug/fix, building/packaging

#659 Make NAM::createRequest() thread-safe
  Quotient/connectiondata.cpp
  Quotient/connectiondata.h
  Quotient/events/filesourceinfo.cpp
  Quotient/events/filesourceinfo.h
  Quotient/jobs/basejob.cpp
  Quotient/mxcreply.cpp
  Quotient/mxcreply.h
  Quotient/networkaccessmanager.cpp
  Quotient/networkaccessmanager.h
  Quotient/room.cpp
  autotests/testutils.cpp
Labels: bug/fix

#661 Remove Room::reset*Count() functions
  Quotient/room.cpp
  Quotient/room.h
Labels: enhancement

#660 Reduce QByteArray/QString conversions further
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
  Quotient/connectiondata.cpp
  Quotient/connectiondata.h
  Quotient/connectionencryptiondata_p.cpp
  Quotient/connectionencryptiondata_p.h
  Quotient/database.cpp
  Quotient/database.h
  Quotient/e2ee/e2ee_common.h
  Quotient/e2ee/qolmaccount.cpp
  Quotient/e2ee/qolminboundsession.cpp
  Quotient/e2ee/qolminboundsession.h
  Quotient/e2ee/qolmsession.cpp
  Quotient/e2ee/qolmsession.h
  Quotient/room.cpp
  Quotient/room.h
  Quotient/ssosession.cpp
  autotests/testolmaccount.cpp
  autotests/testolmutility.cpp
  quotest/quotest.cpp
Labels: enhancement
