Repository quotient-im/libQuotient, pull requests merged in 2024-11, with the labels that each got.

#821 MediaThumbnailJob: Look for the correct spec version for auth media
  Quotient/jobs/mediathumbnailjob.cpp
Labels: bug/fix

#822 Don't warn about unsupported RoomType values
  Quotient/converters.cpp
  Quotient/converters.h
  Quotient/events/roomcreateevent.cpp
  Quotient/events/roommemberevent.cpp
Labels: enhancement

#826 More cleanup and code modernization (still 0.9 compatible)
  Quotient/avatar.h
  Quotient/connection.cpp
  Quotient/connectiondata.cpp
  Quotient/converters.h
  Quotient/events/accountdataevents.h
  Quotient/events/event.h
  Quotient/events/eventcontent.h
  Quotient/events/stateevent.h
  Quotient/mxcreply.cpp
  Quotient/mxcreply.h
  Quotient/room.cpp
  Quotient/util.h
  quotest/quotest.cpp
Labels: bug/fix, enhancement

#827 Fix saving access token to keychain
  Quotient/connection.cpp
Labels: regression

#835 Fix downloading encrypted files to a temporary location
  Quotient/jobs/downloadfilejob.cpp
Labels: bug/fix

#840 Cleanup again (and a new algorithm)
  Quotient/jobs/basejob.h
  Quotient/jobs/downloadfilejob.cpp
  Quotient/ranges_extras.h
  Quotient/util.h
  autotests/testolmaccount.cpp
  autotests/testutils.h
  quotest/quotest.cpp
Labels: enhancement
