Repository quotient-im/libQuotient, pull requests merged in 2024-09, with the labels that each got.

#794 Fix a couple of blunders
  Quotient/jobs/basejob.cpp
  Quotient/settings.cpp
  Quotient/settings.h
Labels: bug/fix

#795 State_Default default power level
  Quotient/events/roompowerlevelsevent.cpp
Labels: bug/fix

#796 RoomMember::avatar()
  Quotient/avatar.cpp
  Quotient/avatar.h
  Quotient/connection.cpp
  Quotient/room.cpp
  Quotient/room.h
  Quotient/roommember.cpp
  Quotient/roommember.h
  Quotient/user.cpp
  Quotient/user.h
Labels: enhancement

#798 Fixes and cleanup again
  CONTRIBUTING.md
  Quotient/csapi/administrative_contact.cpp
  Quotient/csapi/capabilities.cpp
  Quotient/csapi/content-repo.cpp
  Quotient/csapi/create_room.cpp
  Quotient/csapi/directory.cpp
  Quotient/csapi/filter.cpp
  Quotient/csapi/joining.cpp
  Quotient/csapi/key_backup.cpp
  Quotient/csapi/keys.cpp
  Quotient/csapi/knocking.cpp
  Quotient/csapi/list_joined_rooms.cpp
  Quotient/csapi/list_public_rooms.cpp
  Quotient/csapi/login.cpp
  Quotient/csapi/login_token.cpp
  Quotient/csapi/message_pagination.cpp
  Quotient/csapi/notifications.cpp
  Quotient/csapi/presence.cpp
  Quotient/csapi/pushrules.cpp
  Quotient/csapi/refresh.cpp
  Quotient/csapi/registration.cpp
  Quotient/csapi/registration_tokens.cpp
  Quotient/csapi/relations.cpp
  Quotient/csapi/room_event_by_timestamp.cpp
  Quotient/csapi/room_send.cpp
  Quotient/csapi/room_state.cpp
  Quotient/csapi/room_upgrades.cpp
  Quotient/csapi/search.cpp
  Quotient/csapi/space_hierarchy.cpp
  Quotient/csapi/threads_list.cpp
  Quotient/csapi/users.cpp
  Quotient/csapi/versions.cpp
  Quotient/csapi/whoami.cpp
  Quotient/jobs/basejob.cpp
  Quotient/jobs/basejob.h
  Quotient/room.h
  Quotient/roommember.h
  gtad/operation.cpp.mustache
Labels: enhancement, documentation

#789 Add helper functions for replies and threads to RoomMessageEvent
  Quotient/events/eventrelation.cpp
  Quotient/events/eventrelation.h
  Quotient/events/roommessageevent.cpp
  Quotient/events/roommessageevent.h
Labels: enhancement

#799 Better power level checking, part 1
  Quotient/events/event.cpp
  Quotient/events/event.h
  Quotient/events/roomevent.cpp
  Quotient/events/roomevent.h
  Quotient/events/roompowerlevelsevent.cpp
  Quotient/events/roompowerlevelsevent.h
  Quotient/room.cpp
  Quotient/room.h
  Quotient/roomstateview.h
Labels: enhancement

#803 There's always place for more fixes
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
  Quotient/connectiondata.cpp
  Quotient/connectiondata.h
  Quotient/connectionencryptiondata_p.cpp
  Quotient/connectionencryptiondata_p.h
  Quotient/networkaccessmanager.cpp
  Quotient/networkaccessmanager.h
  Quotient/room.cpp
  Quotient/util.h
  autotests/testolmaccount.cpp
  autotests/testutils.h
  quotest/quotest.cpp
Labels: bug/fix, regression
