Repository quotient-im/libQuotient, pull requests merged in 2024-04, with the labels that each got.

#729 Create an event for m.room.server_acl
  Quotient/events/simplestateevents.h
Labels: enhancement

#730 Direct Chat Encryption Default
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
Labels: enhancement

#735 Fix some deprecation warnings
  Quotient/util.h
  quotest/quotest.cpp
Labels: building/packaging

#738 Last fixes before 0.8.2
  Quotient/connection.cpp
  Quotient/e2ee/qolmsession.h
  Quotient/networkaccessmanager.cpp
  Quotient/room.cpp
  Quotient/user.cpp
  quotest/quotest.cpp
Labels: enhancement

#739 Release 0.8.2
  .clang-tidy
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: release

#740 Bump API version
  CMakeLists.txt
Labels: building/packaging

#742 Forward-port 0.8.x fixes
  .clang-tidy
  CONTRIBUTING.md
  Quotient/connection.cpp
  Quotient/e2ee/qolmsession.h
  Quotient/networkaccessmanager.cpp
  Quotient/room.cpp
  Quotient/user.cpp
  README.md
  SECURITY.md
  quotest/quotest.cpp
Labels: enhancement

#743 Rip the Deprecated User Stuff
  Quotient/connection.cpp
  Quotient/room.cpp
  Quotient/room.h
  Quotient/user.cpp
  Quotient/user.h
  quotest/quotest.cpp
Labels: enhancement

#744 Up requirements, modernize and refresh some code
  .clang-tidy
  .github/workflows/ci.yml
  CMakeLists.txt
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connectiondata.h
  Quotient/converters.h
  Quotient/e2ee/cryptoutils.cpp
  Quotient/e2ee/e2ee_common.cpp
  Quotient/e2ee/e2ee_common.h
  Quotient/e2ee/qolmsession.cpp
  Quotient/eventitem.h
  Quotient/events/callevents.h
  Quotient/events/encryptionevent.h
  Quotient/events/event.cpp
  Quotient/events/event.h
  Quotient/events/eventloader.h
  Quotient/events/eventrelation.h
  Quotient/events/reactionevent.h
  Quotient/events/receiptevent.h
  Quotient/events/roommemberevent.h
  Quotient/events/roommessageevent.cpp
  Quotient/events/roommessageevent.h
  Quotient/events/simplestateevents.h
  Quotient/events/stateevent.h
  Quotient/expected.h
  Quotient/jobs/basejob.cpp
  Quotient/jobs/syncjob.h
  Quotient/omittable.h
  Quotient/qt_connection_util.h
  Quotient/room.cpp
  Quotient/room.h
  Quotient/syncdata.h
  README.md
  autotests/testgroupsession.cpp
  quotest/quotest.cpp
Labels: enhancement

#748 Upgrade build configuration
  .github/workflows/ci.yml
  CMakeLists.txt
  Quotient/connection_p.h
  Quotient/connectionencryptiondata_p.h
  autotests/CMakeLists.txt
Labels: building/packaging

#747 Make RoomMember usage more convenient
  Quotient/room.cpp
  Quotient/room.h
  Quotient/roommember.cpp
  Quotient/roommember.h
Labels: enhancement

#749 More QUOTIENT_API
  Quotient/application-service/definitions/location.h
  Quotient/application-service/definitions/protocol.h
  Quotient/application-service/definitions/user.h
  Quotient/csapi/admin.h
  Quotient/csapi/administrative_contact.h
  Quotient/csapi/capabilities.h
  Quotient/csapi/create_room.h
  Quotient/csapi/definitions/auth_data.h
  Quotient/csapi/definitions/client_device.h
  Quotient/csapi/definitions/cross_signing_key.h
  Quotient/csapi/definitions/device_keys.h
  Quotient/csapi/definitions/event_filter.h
  Quotient/csapi/definitions/key_backup_data.h
  Quotient/csapi/definitions/openid_token.h
  Quotient/csapi/definitions/public_rooms_response.h
  Quotient/csapi/definitions/push_condition.h
  Quotient/csapi/definitions/push_rule.h
  Quotient/csapi/definitions/push_ruleset.h
  Quotient/csapi/definitions/request_email_validation.h
  Quotient/csapi/definitions/request_msisdn_validation.h
  Quotient/csapi/definitions/request_token_response.h
  Quotient/csapi/definitions/room_event_filter.h
  Quotient/csapi/definitions/room_key_backup.h
  Quotient/csapi/definitions/sync_filter.h
  Quotient/csapi/definitions/third_party_signed.h
  Quotient/csapi/definitions/user_identifier.h
  Quotient/csapi/definitions/wellknown/full.h
  Quotient/csapi/definitions/wellknown/homeserver.h
  Quotient/csapi/definitions/wellknown/identity_server.h
  Quotient/csapi/keys.h
  Quotient/csapi/list_public_rooms.h
  Quotient/csapi/login.h
  Quotient/csapi/notifications.h
  Quotient/csapi/pusher.h
  Quotient/csapi/rooms.h
  Quotient/csapi/search.h
  Quotient/csapi/space_hierarchy.h
  Quotient/csapi/support.h
  Quotient/csapi/tags.h
  Quotient/csapi/users.h
  Quotient/syncdata.h
  gtad/gtad.yaml
  gtad/operation.h.mustache
Labels: enhancement
