Repository quotient-im/libQuotient, pull requests merged in 2024-08, with the labels that each got.

#784 Fix authenticated media
  Quotient/connectiondata.cpp
  Quotient/jobs/downloadfilejob.cpp
  Quotient/networkaccessmanager.cpp
  Quotient/networkaccessmanager.h
  Quotient/util.h
Labels: bug/fix

#777 Prepare libQuotient for operating without being able to reach the server
  .github/workflows/ci.yml
  Quotient/accountregistry.cpp
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connectionencryptiondata_p.cpp
  Quotient/connectionencryptiondata_p.h
Labels: enhancement

#786 Another round of cleanup
  .github/workflows/ci.yml
  Quotient/accountregistry.cpp
  Quotient/connection.cpp
  Quotient/connection_p.h
  Quotient/connectiondata.cpp
  Quotient/connectiondata.h
  Quotient/e2ee/cryptoutils.cpp
  Quotient/e2ee/e2ee_common.h
  Quotient/e2ee/qolmaccount.cpp
  Quotient/jobs/basejob.cpp
  Quotient/jobs/basejob.h
  Quotient/keyverificationsession.cpp
  Quotient/networkaccessmanager.cpp
  Quotient/room.cpp
  Quotient/util.h
  autotests/callcandidateseventtest.cpp
  autotests/testolmaccount.cpp
  autotests/testolmutility.cpp
  quotest/quotest.cpp
Labels: bug/fix, enhancement

#787 Event iD Display
  Quotient/events/roomevent.cpp
  Quotient/events/roomevent.h
Labels: enhancement

#788 Fix GCC -Wattributes warnings
  Quotient/jobs/jobhandle.h
Labels: building/packaging

#792 0.9 beta
  CMakeLists.txt
Labels: release
