Repository quotient-im/libQuotient, pull requests merged in 2024-07, with the labels that each got.

#761 Implement exporting megolm sessions to a file
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connectionencryptiondata_p.cpp
  Quotient/database.cpp
  Quotient/database.h
  Quotient/e2ee/sssshandler.cpp
  Quotient/keyimport.cpp
  Quotient/keyimport.h
  Quotient/room.cpp
  Quotient/room.h
  autotests/testkeyimport.cpp
Labels: enhancement

#769 Fix FTBFS after the previous PR
  Quotient/room.h
Labels: bug/fix

#772 Deserialize CBOR data without one allocation per value
  CMakeLists.txt
  Quotient/syncdata.cpp
Labels: enhancement

#767 Add a promise/future pair to PendingEventItem
  Quotient/eventitem.h
  Quotient/room.cpp
  Quotient/room.h
  quotest/quotest.cpp
Labels: enhancement

#775 Code modernisation + newer Synapse for autotests
  Quotient/e2ee/cryptoutils.cpp
  Quotient/e2ee/e2ee_common.cpp
  Quotient/e2ee/e2ee_common.h
  Quotient/e2ee/qolminboundsession.cpp
  Quotient/e2ee/qolmoutboundsession.cpp
  Quotient/events/accountdataevents.h
  Quotient/events/event.h
  Quotient/events/roommessageevent.cpp
  Quotient/events/roommessageevent.h
  Quotient/jobs/basejob.cpp
  Quotient/keyimport.cpp
  autotests/adjust-config.sh
  autotests/register-users.sh
  autotests/setup-tests.sh
  autotests/testutils.cpp
Labels: enhancement

#778 Bug/regression fixes and some cleanup
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
  Quotient/connectiondata.cpp
  Quotient/connectiondata.h
  Quotient/e2ee/e2ee_common.h
  Quotient/e2ee/qolmaccount.cpp
  Quotient/e2ee/qolmsession.cpp
  Quotient/events/encryptionevent.h
  Quotient/events/roommemberevent.h
  Quotient/events/single_key_value.h
  Quotient/expected.h
  Quotient/jobs/basejob.cpp
  Quotient/jobs/basejob.h
  Quotient/jobs/jobhandle.h
  Quotient/jobs/requestdata.h
  Quotient/util.cpp
  Quotient/util.h
  autotests/utiltests.cpp
Labels: enhancement, regression
