Repository quotient-im/libQuotient, pull requests merged in 2024-05, with the labels that each got.

#746 Clean up the rest of the User stuff around connection
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
  Quotient/user.cpp
  quotest/quotest.cpp
Labels: enhancement

#630 Implement Cross-Signing
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connectionencryptiondata_p.cpp
  Quotient/connectionencryptiondata_p.h
  Quotient/database.cpp
  Quotient/database.h
  Quotient/e2ee/cryptoutils.cpp
  Quotient/e2ee/cryptoutils.h
  Quotient/e2ee/sssshandler.cpp
  Quotient/e2ee/sssshandler.h
  Quotient/events/keyverificationevent.h
  Quotient/events/roommessageevent.cpp
  Quotient/keyverificationsession.cpp
  Quotient/keyverificationsession.h
  Quotient/room.cpp
  Quotient/room.h
  autotests/CMakeLists.txt
  autotests/cross_signing_data.json
  autotests/testcrosssigning.cpp
Labels: enhancement, E2EE

#754 Job handles, aka Here comes the future
  .clang-format
  CMakeLists.txt
  Quotient/avatar.cpp
  Quotient/avatar.h
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
  Quotient/connectionencryptiondata_p.cpp
  Quotient/e2ee/sssshandler.cpp
  Quotient/jobs/basejob.cpp
  Quotient/jobs/basejob.h
  Quotient/jobs/jobhandle.h
  Quotient/qt_connection_util.h
  Quotient/room.cpp
  Quotient/room.h
  Quotient/user.cpp
  Quotient/user.h
  quotest/quotest.cpp
Labels: enhancement

#758 Implement importing megolm keys from a file
  CMakeLists.txt
  Quotient/e2ee/cryptoutils.cpp
  Quotient/e2ee/cryptoutils.h
  Quotient/keyimport.cpp
  Quotient/keyimport.h
  autotests/CMakeLists.txt
  autotests/key-export.data
  autotests/testkeyimport.cpp
Labels: enhancement, E2EE

#759 Fix tests not being executed in CI
  .github/workflows/ci.yml
  autotests/CMakeLists.txt
  cmake/QuotientConfig.cmake.in
Labels: bug/fix, building/packaging

#760 Assorted quality of life tweaks
  CMakeLists.txt
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connectionencryptiondata_p.cpp
  Quotient/connectionencryptiondata_p.h
  Quotient/converters.h
  Quotient/e2ee/e2ee_common.cpp
  Quotient/e2ee/e2ee_common.h
  Quotient/eventitem.h
  Quotient/events/encryptedevent.cpp
  Quotient/events/event.h
  Quotient/events/eventrelation.cpp
  Quotient/events/eventrelation.h
  Quotient/events/keyverificationevent.h
  Quotient/events/roomevent.h
  Quotient/events/roommessageevent.cpp
  Quotient/events/stateevent.h
  Quotient/jobs/jobhandle.h
  Quotient/jobs/mediathumbnailjob.h
  Quotient/qt_connection_util.h
  Quotient/ranges_extras.h
  Quotient/room.cpp
  Quotient/room.h
  Quotient/util.h
  quotest/quotest.cpp
Labels: enhancement
