Repository quotient-im/libQuotient, pull requests merged in 2024-10, with the labels that each got.

#805 Reply to All RoomMessageEvents
  Quotient/events/eventrelation.cpp
  Quotient/events/roommessageevent.cpp
  Quotient/events/roommessageevent.h
Labels: enhancement

#808 Update to the released Matrix 1.12
  Quotient/jobs/basejob.cpp
  Quotient/jobs/basejob.h
Labels: enhancement

#809 Fixes before 0.9 RC2
  Quotient/csapi/profile.cpp
  Quotient/eventitem.cpp
  Quotient/events/event.h
  Quotient/events/eventcontent.h
  Quotient/events/roommessageevent.cpp
  Quotient/events/roommessageevent.h
  Quotient/events/simplestateevents.h
  Quotient/room.cpp
  Quotient/room.h
  Quotient/util.h
  autotests/testolmaccount.cpp
  quotest/quotest.cpp
Labels: bug/fix, regression

#812 Rework RoomMessageEvent content API again
  Quotient/eventitem.cpp
  Quotient/events/eventcontent.cpp
  Quotient/events/eventcontent.h
  Quotient/events/filesourceinfo.cpp
  Quotient/events/filesourceinfo.h
  Quotient/events/roommessageevent.cpp
  Quotient/events/roommessageevent.h
  Quotient/room.cpp
  quotest/quotest.cpp
Labels: regression

#815 0.9 RC3
  CMakeLists.txt
Labels: release

#816 pendingEventAdded event param
  Quotient/room.cpp
  Quotient/room.h
Labels: enhancement

#818 Release 0.9
  CMakeLists.txt
Labels: release

#819 Add isonline parameter to connection
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
Labels: enhancement
