Repository quotient-im/libQuotient, pull requests merged in 2025-08, with the labels that each got.

#898 Backporting to 0.9 things previously landed in 0.10
  CMakeLists.txt
  Quotient/connection.cpp
  Quotient/connectionencryptiondata_p.cpp
  Quotient/jobs/downloadfilejob.cpp
  Quotient/jobs/syncjob.cpp
  Quotient/room.cpp
  Quotient/room.h
  Quotient/syncdata.cpp
Labels: bug/fix, enhancement

#897 Support room version 12
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/events/roomcreateevent.cpp
  Quotient/events/roomcreateevent.h
  Quotient/room.cpp
  Quotient/room.h
Labels: enhancement

#902 Allow handling key verification start events from other devices
  Quotient/keyverificationsession.cpp
Labels: bug/fix

#905 Fix qt warning about too high timer intervals
  Quotient/jobs/syncjob.cpp
Labels: enhancement
