Repository quotient-im/libQuotient, pull requests merged in 2025-01, with the labels that each got.

#850 OIDC-awareness
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
  Quotient/csapi/login.h
  Quotient/ranges_extras.h
  Quotient/ssosession.cpp
  Quotient/ssosession.h
  gtad/gtad.yaml
Labels: enhancement

#806 Support event relations on all post message functions
  Quotient/room.cpp
  Quotient/room.h
  quotest/quotest.cpp
Labels: enhancement

#851 Fix FTBFS caused by a mis-merge in #806
  quotest/quotest.cpp
Labels: bug/fix

#852 Support event relations on all post message functions
  Quotient/room.cpp
  Quotient/room.h
  quotest/quotest.cpp
Labels: enhancement

#853 OIDC awareness - 0.9.x
  Quotient/connection.cpp
  Quotient/connection.h
  Quotient/connection_p.h
  Quotient/csapi/login.h
  Quotient/ranges_extras.h
  Quotient/ssosession.cpp
  Quotient/ssosession.h
  gtad/gtad.yaml
Labels: enhancement

#855 Refactor Settings
  Quotient/settings.cpp
  Quotient/settings.h
  autotests/testsettings.cpp
Labels: enhancement

#857 Minor fixes - 0.9
  Quotient/connection.cpp
  Quotient/room.cpp
Labels: enhancement

#858 Minor fixes - 0.10
  Quotient/connection.cpp
  Quotient/room.cpp
Labels: bug/fix, enhancement

#859 Bump the version to 0.10 alpha; stop using old API
  CMakeLists.txt
  Quotient/connectionencryptiondata_p.cpp
  Quotient/events/roommessageevent.cpp
  Quotient/room.cpp
  Quotient/room.h
  Quotient/util.h
Labels: building/packaging

#849 New Thread Signal
  Quotient/room.cpp
  Quotient/room.h
Labels: enhancement
